//
// Created by sun on 11/14/16.
//

#include "htmldata.h"

const myhashset<myu32string> void_elements {
        "!doctype",
        "area",
        "base",
        "br",
        "col",
        "embed",
        "hr",
        "img",
        "input",
        "keygen",
        "link",
        "menuitem",
        "meta",
        "param",
        "source",
        "track",
        "wbr"
};

const myhashmap<myu32string, char32_t> escape_string {
        mymake_pair("amp",      0x26),
        mymake_pair("lt",       0x3c),
        mymake_pair("gt",       0x3e),
        mymake_pair("Agrave",   0xc0),
        mymake_pair("Aacute",   0xc1),
        mymake_pair("Acirc",    0xc2),
        mymake_pair("Atilde",   0xc3),
        mymake_pair("Auml",     0xc4),
        mymake_pair("Aring",    0xc5),
        mymake_pair("AElig",    0xc6),
        mymake_pair("Ccedil",   0xc7),
        mymake_pair("Egrave",   0xc8),
        mymake_pair("Eacute",   0xc9),
        mymake_pair("Ecirc",    0xca),
        mymake_pair("Euml",     0xcb),
        mymake_pair("Igrave",   0xcc),
        mymake_pair("Iacute",   0xcd),
        mymake_pair("Icirc",    0xce),
        mymake_pair("Iuml",     0xcf),
        mymake_pair("ETH",      0xd0),
        mymake_pair("Ntilde",   0xd1),
        mymake_pair("Ograve",   0xd2),
        mymake_pair("Oacute",   0xd3),
        mymake_pair("Ocirc",    0xd4),
        mymake_pair("Otilde",   0xd5),
        mymake_pair("Ouml",     0xd6),
        mymake_pair("Oslash",   0xd8),
        mymake_pair("Ugrave",   0xd9),
        mymake_pair("Uacute",   0xda),
        mymake_pair("Ucirc",    0xdb),
        mymake_pair("Uuml",     0xdc),
        mymake_pair("Yacute",   0xdd),
        mymake_pair("THORN",    0xde),
        mymake_pair("szlig",    0xdf),
        mymake_pair("agrave",   0xe0),
        mymake_pair("aacute",   0xe1),
        mymake_pair("acirc",    0xe2),
        mymake_pair("atilde",   0xe3),
        mymake_pair("auml",     0xe4),
        mymake_pair("aring",    0xe5),
        mymake_pair("aelig",    0xe6),
        mymake_pair("ccedil",   0xe7),
        mymake_pair("egrave",   0xe8),
        mymake_pair("eacute",   0xe9),
        mymake_pair("ecirc",    0xea),
        mymake_pair("euml",     0xeb),
        mymake_pair("igrave",   0xec),
        mymake_pair("iacute",   0xed),
        mymake_pair("icirc",    0xee),
        mymake_pair("iuml",     0xef),
        mymake_pair("eth",      0xf0),
        mymake_pair("ntilde",   0xf1),
        mymake_pair("ograve",   0xf2),
        mymake_pair("oacute",   0xf3),
        mymake_pair("ocirc",    0xf4),
        mymake_pair("otilde",   0xf5),
        mymake_pair("ouml",     0xf6),
        mymake_pair("oslash",   0xf8),
        mymake_pair("ugrave",   0xf9),
        mymake_pair("uacute",   0xfa),
        mymake_pair("ucirc",    0xfb),
        mymake_pair("uuml",     0xfc),
        mymake_pair("yacute",   0xfd),
        mymake_pair("thorn",    0xfe),
        mymake_pair("yuml",     0xff),
        mymake_pair("nbsp",     0xa0),
        mymake_pair("iexcl",    0xa1),
        mymake_pair("cent",     0xa2),
        mymake_pair("pound",    0xa3),
        mymake_pair("curren",   0xa4),
        mymake_pair("yen",      0xa5),
        mymake_pair("brvbar",   0xa6),
        mymake_pair("sect",     0xa7),
        mymake_pair("uml",      0xa8),
        mymake_pair("copy",     0xa9),
        mymake_pair("ordf",     0xaa),
        mymake_pair("laquo",    0xab),
        mymake_pair("not",      0xac),
        mymake_pair("shy",      0xad),
        mymake_pair("reg",      0xae),
        mymake_pair("macr",     0xaf),
        mymake_pair("deg",      0xb0),
        mymake_pair("plusmn",   0xb1),
        mymake_pair("sup2",     0xb2),
        mymake_pair("sup3",     0xb3),
        mymake_pair("acute",    0xb4),
        mymake_pair("micro",    0xb5),
        mymake_pair("para",     0xb6),
        mymake_pair("cedil",    0xb8),
        mymake_pair("sup1",     0xb9),
        mymake_pair("ordm",     0xba),
        mymake_pair("raquo",    0xbb),
        mymake_pair("frac14",   0xbc),
        mymake_pair("frac12",   0xbd),
        mymake_pair("frac34",   0xbe),
        mymake_pair("iquest",   0xbf),
        mymake_pair("times",    0xd7),
        mymake_pair("divide",   0xf7),
        mymake_pair("forall",   0x2200),
        mymake_pair("part",     0x2202),
        mymake_pair("exist",    0x2203),
        mymake_pair("empty",    0x2205),
        mymake_pair("nabla",    0x2207),
        mymake_pair("isin",     0x2208),
        mymake_pair("notin",    0x2209),
        mymake_pair("ni",       0x220b),
        mymake_pair("prod",     0x220f),
        mymake_pair("sum",      0x2211),
        mymake_pair("minus",    0x2212),
        mymake_pair("lowast",   0x2217),
        mymake_pair("radic",    0x221a),
        mymake_pair("prop",     0x221d),
        mymake_pair("infin",    0x221e),
        mymake_pair("ang",      0x2220),
        mymake_pair("and",      0x2227),
        mymake_pair("or",       0x2228),
        mymake_pair("cap",      0x2229),
        mymake_pair("cup",      0x222a),
        mymake_pair("int",      0x222b),
        mymake_pair("there4",   0x2234),
        mymake_pair("sim",      0x223c),
        mymake_pair("cong",     0x2245),
        mymake_pair("asymp",    0x2248),
        mymake_pair("ne",       0x2260),
        mymake_pair("equiv",    0x2261),
        mymake_pair("le",       0x2264),
        mymake_pair("ge",       0x2265),
        mymake_pair("sub",      0x2282),
        mymake_pair("sup",      0x2283),
        mymake_pair("nsub",     0x2284),
        mymake_pair("sube",     0x2286),
        mymake_pair("supe",     0x2287),
        mymake_pair("oplus",    0x2295),
        mymake_pair("otimes",   0x2297),
        mymake_pair("perp",     0x22a5),
        mymake_pair("sdot",     0x22c5),
        mymake_pair("Alpha",    0x391),
        mymake_pair("Beta",     0x392),
        mymake_pair("Gamma",    0x393),
        mymake_pair("Delta",    0x394),
        mymake_pair("Epsilon",  0x395),
        mymake_pair("Zeta",     0x396),
        mymake_pair("Eta",      0x397),
        mymake_pair("Theta",    0x398),
        mymake_pair("Iota",     0x399),
        mymake_pair("Kappa",    0x39a),
        mymake_pair("Lambda",   0x39b),
        mymake_pair("Mu",       0x39c),
        mymake_pair("Nu",       0x39d),
        mymake_pair("Xi",       0x39e),
        mymake_pair("Omicron",  0x39f),
        mymake_pair("Pi",       0x3a0),
        mymake_pair("Rho",      0x3a1),
        mymake_pair("Sigma",    0x3a3),
        mymake_pair("Tau",      0x3a4),
        mymake_pair("Upsilon",  0x3a5),
        mymake_pair("Phi",      0x3a6),
        mymake_pair("Chi",      0x3a7),
        mymake_pair("Psi",      0x3a8),
        mymake_pair("Omega",    0x3a9),
        mymake_pair("alpha",    0x3b1),
        mymake_pair("beta",     0x3b2),
        mymake_pair("gamma",    0x3b3),
        mymake_pair("delta",    0x3b4),
        mymake_pair("epsilon",  0x3b5),
        mymake_pair("zeta",     0x3b6),
        mymake_pair("eta",      0x3b7),
        mymake_pair("theta",    0x3b8),
        mymake_pair("iota",     0x3b9),
        mymake_pair("kappa",    0x3ba),
        mymake_pair("lambda",   0x3bb),
        mymake_pair("mu",       0x3bc),
        mymake_pair("nu",       0x3bd),
        mymake_pair("xi",       0x3be),
        mymake_pair("omicron",  0x3bf),
        mymake_pair("pi",       0x3c0),
        mymake_pair("rho",      0x3c1),
        mymake_pair("sigmaf",   0x3c2),
        mymake_pair("sigma",    0x3c3),
        mymake_pair("tau",      0x3c4),
        mymake_pair("upsilon",  0x3c5),
        mymake_pair("phi",      0x3c6),
        mymake_pair("chi",      0x3c7),
        mymake_pair("psi",      0x3c8),
        mymake_pair("omega",    0x3c9),
        mymake_pair("thetasym", 0x3d1),
        mymake_pair("upsih",    0x3d2),
        mymake_pair("piv",      0x3d6),
        mymake_pair("OElig",    0x152),
        mymake_pair("oelig",    0x153),
        mymake_pair("Scaron",   0x160),
        mymake_pair("scaron",   0x161),
        mymake_pair("Yuml",     0x178),
        mymake_pair("fnof",     0x192),
        mymake_pair("circ",     0x2c6),
        mymake_pair("tilde",    0x2dc),
        mymake_pair("ensp",     0x2002),
        mymake_pair("emsp",     0x2003),
        mymake_pair("thinsp",   0x2009),
        mymake_pair("zwnj",     0x200c),
        mymake_pair("zwj",      0x200d),
        mymake_pair("lrm",      0x200e),
        mymake_pair("rlm",      0x200f),
        mymake_pair("ndash",    0x2013),
        mymake_pair("mdash",    0x2014),
        mymake_pair("lsquo",    0x2018),
        mymake_pair("rsquo",    0x2019),
        mymake_pair("sbquo",    0x201a),
        mymake_pair("ldquo",    0x201c),
        mymake_pair("rdquo",    0x201d),
        mymake_pair("bdquo",    0x201e),
        mymake_pair("dagger",   0x2020),
        mymake_pair("Dagger",   0x2021),
        mymake_pair("bull",     0x2022),
        mymake_pair("hellip",   0x2026),
        mymake_pair("permil",   0x2030),
        mymake_pair("prime",    0x2032),
        mymake_pair("Prime",    0x2033),
        mymake_pair("lsaquo",   0x2039),
        mymake_pair("rsaquo",   0x203a),
        mymake_pair("oline",    0x203e),
        mymake_pair("euro",     0x20ac),
        mymake_pair("trade",    0x2122),
        mymake_pair("larr",     0x2190),
        mymake_pair("uarr",     0x2191),
        mymake_pair("rarr",     0x2192),
        mymake_pair("darr",     0x2193),
        mymake_pair("harr",     0x2194),
        mymake_pair("crarr",    0x21b5),
        mymake_pair("lceil",    0x2308),
        mymake_pair("rceil",    0x2309),
        mymake_pair("lfloor",   0x230a),
        mymake_pair("rfloor",   0x230b),
        mymake_pair("loz",      0x25ca),
        mymake_pair("spades",   0x2660),
        mymake_pair("clubs",    0x2663),
        mymake_pair("hearts",   0x2665),
        mymake_pair("diams",    0x2666),
        mymake_pair("middot",   0xb7)
};
